/*
 * generated by Xtext 2.18.0
 */
package net.technearts.pipe


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PipeStandaloneSetup extends PipeStandaloneSetupGenerated {

	def static void doSetup() {
		new PipeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
