/*
 * generated by Xtext 2.16.0
 */
package net.technearts.pipe


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PipeRuntimeModule extends AbstractPipeRuntimeModule {
}
