/*
 * generated by Xtext 2.16.0
 */
package net.technearts.pipe.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PipeValidator extends AbstractPipeValidator {
	
}
