/*
 * generated by Xtext 2.18.0
 */
package net.technearts.pipe.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class PipeWebModule extends AbstractPipeWebModule {
}
